services:
  - type: web
    name: praveen-portfolio-api
    env: node
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: HMAC_SECRET
        generateValue: true
